### ISSUE TITLE
Is this adapter not implemented?

### ISSUE THREAD

**Issue by zhht1204** [jcasbin/string-adapter#1]
Hi,

I'm trying to use casbin in Java, and found that only redis/db policy adapters are supported officially in the documents.

Is there any plan about this implemention?

P.S. Since I'm not very proficient with Java, I'm not confident to implement my own one that work in a best practice way. 😢

**Comment by hsluoyz** [comment]
@zhht1204 do you expect something like this? https://github.com/jcasbin/string-adapter/issues/2

**Comment by zhht1204** [comment]
> @zhht1204 do you expect something like this? #2

Yeah seems quite like. A Java implemention of it. 😄

**Comment by hsluoyz** [comment]
@zhht1204  Fixed by: https://github.com/jcasbin/string-adapter/pull/3
